cmake_minimum_required(VERSION 3.16)
project(cloudgrasp_lab)
find_package(ament_cmake REQUIRED)
find_package(rclcpp_action REQUIRED)
find_package(grasping_msgs REQUIRED)
find_package(std_msgs REQUIRED)
find_package(rclcpp REQUIRED)
find_package(moveit_ros_planning_interface REQUIRED)
add_executable(lab_motion src/lab_motion.cpp)
ament_target_dependencies(lab_motion rclcpp moveit_ros_planning_interface)
add_executable(lab_task src/task.cpp)
ament_target_dependencies(lab_task rclcpp rclcpp_action moveit_ros_planning_interface grasping_msgs std_msgs)
install(TARGETS lab_motion lab_task DESTINATION lib/${PROJECT_NAME})
install(DIRECTORY launch worlds config DESTINATION share/${PROJECT_NAME})
ament_package()
